---
title: "GoalRep_otherRating_analysis"
author: "Bernice Cheung"
date: "4/14/2021"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, echo=FALSE,warning=FALSE,message=FALSE}
library(tidyverse)
library(stringr)
library(here)
library(readbulk)
library(readxl)
library(irr)
library(irrNA)
```

load data
```{r}
sona2_raw <- read_bulk(directory = here("coded_data", "SONA2"), fun = read_excel, sheet = 1, col_names = T, n_max = 180)
```

recode data
```{r}
# group variables based on weather it's unipolar / bipolar
uni_col <- c("measurability", "meaningfulness", "importance", "instrumentality", "visibility", "external_importance","affordance")
bi_col <- c("social_desirability", "external_motivation", "introjected_motivation", "identified_motivation", "intrinsic_motivation", "ought_motivation", "ideal_motivation", "basic_needs", "commonality", "control", "clarity")

# recode variables
sona2_clean <-sona2_raw %>%
  mutate_at(vars(ideal_motivation:affordance),funs(recode(., "1.0" = "1", "2.0" = "2", "3.0" = "3", "4.0" = "4", "5.0" = "5", "6.0" = "6", "7.0" = "7"))) %>%
  mutate_at(vars(uni_col), funs(recode(.,"1: Not at all" = 1, "2" = 2, "3" = 3, "4:Neutral" = 4, "5" = 5, "6" = 6, "7: Very much" = 7, "99: I can't tell" = 99))) %>%
  mutate_at(vars(bi_col), funs(recode(.,"1: Strongly disagree" = 1, "2" = 2, "3" = 3, "4: Neutral" = 4, "5" = 5, "6" = 6, "7: Strongly agree" = 7, "99: I can't tell" = 99, "1: strongly disagree" = 1,"7: strongly agree" = 7, "4:Neutral" = 4))) %>%
  mutate_at(vars(difficulty), funs(recode(., "1: Not at all" = 1, "2" = 2, "3" = 3, "4:Neutral" = 4, "5" = 5, "6" = 6, "7: Very much" = 7, "99: I can't tell" = 99, "7: high level"  = 7, "4: mid level"  = 4))) %>%
  mutate_at(vars(specificity), funs(recode(.,"1: Very general" = 1, "2" = 2, "3" = 3, "4: moderate" = 4, "5" = 5, "6" = 6, "7" = 7, "99: I can't tell" = 99))) %>%
  mutate_at(vars(approach_avoidance), funs(recode(.,"1: An approach goal" = 1, "2" = 2, "3" = 3, "4: neither approach nor avoidance" = 4, "5" = 5, "6" = 6, "7: An avoidance goal" = 7, "99: I can't tell" = 99))) %>%
  mutate_at(vars(attainment_maintenance), funs(recode(.,"1: An attainment goal" = 1, "2" = 2, "3" = 3, "4" = 4, "5" = 5, "6" = 6, "7: An maintenance goal" = 7, "99: I can't tell" = 99))) %>%
  mutate_at(vars(attainability), funs(recode(.,"1: 0%" = 1, "2: 10%" = 2, "3: 20%" = 3, "4: 30%" = 4, "5: 40%" = 5, "6: 50%" = 6, "6:50%" = 6,"7: 60%" = 7, "8: 70%" = 8,"9: 80%" = 9,"10: 90%" = 10,"11: 100%" = 11,"99: I can't tell" = 99))) %>%
  mutate_at(vars(c(attractiveness_achievement, attractiveness_progress)), funs(recode(.,"1: Not at all" = 1, "2: A little good" = 2, "3: Somewhat good" = 3, "4:Good" = 4, "5: Very good" = 5, "6: Great" = 6, "7: One of the best feelings" = 7,"99: I can't tell" = 99))) %>%
  mutate_at(vars(construal_level), funs(recode(.,"1: low level" = 1, "2" = 2, "3" = 3, "4: mid level" = 4, "5" = 5, "6" = 6, "7: High Level" = 7, "99: I can't tell" = 99))) %>%
  mutate_if(is.numeric, list(~na_if(., 99))) %>%
  rowwise() %>%
  mutate(ra = str_sub(File, start = (nchar("goalRating_sona2_") + 1), end = -14L)) %>%
  select(-File)

```

Loop through each dimension and calculate twoway agreement ICC

```{r}
# Extract dimension names (exclude connectivity)
varNames <- names(sona2_clean)[c(4:8,10:21, 23: 25, 27: 28, 30:33)]

# create a df for ICC
iccDf <- data.frame(dimension = varNames, 
                    icc = NA)

# loop through each dimension and extract twoway agreement ICC
rowIdx = 1
for (var in varNames){
  # extract data
  varDf <- sona2_clean[,c("Goals", var, "ra")]
  # transform it to the wide format (exclude duplicated goals)
  varDf_w <-  varDf[-c(111, 115 , 179, 317 , 986, 1024 , 1324, 1364), ] %>%
  spread(ra, var) %>% select(-Goals)
  # calculate ICC
  icc_result <- iccNA(varDf_w, rho0 = 0, conf = 0.95, Cs = 10000, detail = FALSE)
  # extract and score the result to iccDf
  iccDf[rowIdx,2] <- round(icc_result$ICCs[3,1], 3)
  rowIdx = rowIdx + 1
}
```

```{r}
# visualization: 
iccDf %>%
  ggplot(aes(x=dimension, y = icc)) + geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```


